server:
  port: 8080
  context-path:
logging:
 level:
  root: ERROR
  org:
   springframework:
    web: DEBUG
    security: DEBUG
security:
  user:
    password: 123
    name: user
  ignored: /**/**
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
  profiles:
    active: production
---

spring:
    profiles: development
    datasource:
      url: jdbc:h2:mem:contra-tempo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    jpa:
     database: H2
---

spring:
    profiles: production
    datasource:
      url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/heroku_27c9c4cb5bf562d?reconnect=true
      username: bcd784f9327af7
      password: e9b5131c
server:
  port: 8080