server:
  port: 8080
  context-path:
logging:
 level:
  root: ERROR
  org:
   springframework:
    web: DEBUG
    security: DEBUG
security:
  user:
    password: 123
    name: user
  ignored: /**/**
spring:
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  profiles:
    active: development
---

spring:
    profiles: development
    datasource:
      url: jdbc:h2:mem:contra-tempo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    jpa:
     database: H2
---

spring:
    profiles: production
    datasource:
      url: jdbc:postgresql://ec2-184-72-250-49.compute-1.amazonaws.com:5432/d7afbep2826ios?sslmode=require
      username: gjspbrgrojbuxw
      password: vXydZLAjtUdgC24s6t2jRTLPfB
server:
  port: 8080